### user login

POST http://localhost:8080/auth
Content-Type: application/json

{
    "username" : "poli_ppp",
    "password" : "poli0848"
}

### change password

PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "old_password" : "poli0848",
    "new_password" : "084324",
    "confirm_password" : "084324"
}

### to do edit profile

PUT http://localhost:8080
Content-Type: application/json
