### get movie details

GET localhost:8080/movies/2

###show cinema program

GET localhost:8080/cinemas/1/program

###show cinemas

GET localhost:8080/cinemas

### show favourite movies

GET localhost:8080/users/1/favourite-movies

### user login

POST http://localhost:8080/auth
Content-Type: application/json

{
  "email" : "steph@gmail.com",
  "password" : "Stephanie"
}

### change password

PUT http://localhost:8080/users/5
Content-Type: application/json

{
  "old_password" : "Stephanie",
  "new_password" : "Polina09",
  "confirm_password" : "Polina09"
}

### edit profile

PUT http://localhost:8080/users/5/edit
Content-Type: application/json

{
  "first_name": "Stephie",
  "middle_name" : "Pavlova",
  "last_name" : "Petrova",
  "phone_number" : "0852059044",
  "date_of_birth" : "03/02/2020",
  "address" : "Malta",
  "city" : "Dublin"
}
